### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by ntouran** [LLNL/fudge#1]
This would be great to update to python3. 

I tried running [2to3 ](https://docs.python.org/3/library/2to3.html)on it and it handled most of the `print` statements and `xranges` and other things, but the make command ended up giving several C build errors that did not come in the current version under python2, along the lines of:

```
getScatteringMatrices.c:215:64 error: expected '=',',',';','asm' or '__attribute__' before'{' token
```

**Comment by mattooca** [comment]
Hi Nick,
We are preparing another FUDGE release that works with Python 3.6+.  As you noticed, the Python C api changed between v2 and v3  and again between 3.5 and 3.6, so our C extensions also had to be updated.
I don't have a firm estimate yet when the new version will be available, still have a few issues to fix and merge in. In addition to Python 3 compatibility, one major goal for the next release is to support GNDS v2 specifications, which are still being finalized.

**Comment by mattooca** [comment]
Fixed with latest release. We dropped Python-2.7 support and now require Python 3.6 or later.
